services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - "8080:8000"
    volumes:
      # Привязываем локальную папку app (где исходники) внутрь контейнера
      - ./myproject:/usr/src/app
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - DJANGO_SECRET_KEY
      - DEBUG

    depends_on:
      - db
    command: "sleep infinity"


  db:
    image: postgres:15-alpine
    container_name: django_db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      # Пример тома для хранения данных Postgres
      - db_data:/var/lib/postgresql/data

# Описание именованных томов
volumes:
  db_data:
